ServerName localhost
<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
</Directory>
<DirectoryMatch "/var/www/html/(config|lib|database|tests)">
    Require all denied
</DirectoryMatch>
